### ISSUE TITLE
Question: how to align cell value to left or right?

### ISSUE THREAD

**Issue by blue-ht** [insightsengineering/tern#1292]
### Feature description

for example, I want them to be left aligned
![image](https://github.com/user-attachments/assets/038d3e2b-5d8a-4e11-9dfb-96ff33d82dfa)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
This is a question for stack-overflow with nest-rtables tag. Please read the [following ](https://insightsengineering.github.io/rtables/latest-tag/articles/custom_appearance.html?q=align#rows-and-cell-values-alignments)to do what you need. Remember also that screenshots should never be used because they are not searchable. Use {reprex} for reproducible code.
