### ISSUE TITLE
PKCT01 to tern

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#277]
![image](https://user-images.githubusercontent.com/3692541/144770826-dc35c187-ab5a-4959-a123-0d0b9f6f9862.png)

Similar to PKPT03, but instead of split by param in PKPT03, split by visits, then split by sampling time

# Work

Each requires a pull-request 

## Summary Function
- [x] use `s_summary_numeric`

* `n`, `mean`,  `sd`, `cv_mean`,`geometric_mean`, `cv_geometric_mean` , `median`, `minimum`, `maximum`

**Comment by Melkiades** [comment]
I would like to comment here and connect the development that was done until now. Please correct if I am wrong. So first came the request for PKPT03-01 examples in tern #280 with summary and summarize by_cols development. Here an initial example was also provided that is the basis for [tern_pull#559]( https://github.com/insightsengineering/tern/pull/559) where @Nolan-Steed corrected the test according to things in #280 and refactoring from [sme-tasks#183](https://github.com/insightsengineering/sme-tasks/issues/183). This development produced principally two problematics: 1) digits and alignment as described in [formatters#26](https://github.com/insightsengineering/formatters/issues/26) and 2) `NE` replacement for NA in some cases, with the hidden problematic of loosing this variable when the rows are transformed in cols. Now, this is mainly for me, to connect the relevant pieces together, but any addition or consideration is welcomed @shajoezhu

**Comment by Melkiades** [comment]
to do:

- [ ] Significant digits (wont do, can be set manually with format) https://github.com/insightsengineering/formatters/issues/26
- [ ] Alignment https://github.com/insightsengineering/formatters/issues/26, https://github.com/Roche/rtables/issues/218, https://github.com/insightsengineering/formatters/issues/42
- [ ] Create an issue to enhance s_summary.numeric so that it can also return geom mean's confidence interval. For this, it's worth creating kind of a similar function as stat_mean_ci from stat.R _Originally posted by @imazubi in https://github.com/insightsengineering/tern/issues/280#issuecomment-994899904_
- [ ] NE string instead of NaN

**Comment by Melkiades** [comment]
waiting for https://github.com/insightsengineering/formatters/issues/42

**Comment by qiliu1013** [comment]
Hi @shajoezhu, Sorry I lost track on the progress. Should I work on 1/3 and ½ imputation rule  as the next task? No sure if someone already work on it.

**Comment by Melkiades** [comment]
> Hi @shajoezhu, Sorry I lost track on the progress. Should I work on 1/3 and ½ imputation rule as the next task? No sure if someone already work on it.

@qiliu1013 no one is working on it atm. Reference issue is this: https://github.com/insightsengineering/tern/issues/543
