### ISSUE TITLE
Refactoring estimate_odds_ratio function

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#287]
@shajoezhu this PR has fixed the Stratified Analysis section of the Response table output so that it now matches the stream output. There is still an issue with Odds Ratio - the module uses `clogit` to calculate the odds ratio whereas the stream output uses the following custom function which Joel mentions in his code output [here](https://github.com/insightsengineering/tern/issues/74#issuecomment-993786577):

```
odds_ratio <- function(x, conf_level = 0.95) {
  
  theta <- x[1, 1] * x[2, 2] / (x[2, 1] * x[1, 2])
  # Asymptotic standard error
  ase <- sqrt(sum(1 / x))
  ci <- exp(log(theta) + c(-1, 1) * qnorm(0.5 * (1 + conf_level)) * ase)
  
  list(
    estimator = theta,
    se = ase,
    conf.int = ci,
    conf_level = conf_level
  )
}
```

How do you want to go about incorporating this into the module? The module currently uses [estimate_odds_ratio](https://github.com/insightsengineering/tern/blob/59180129f956398a5e9878f16f04377d8e64a176/R/odds_ratio.R#L286) to calculate OR, which uses a different format than the above function.

_Originally posted by @edelarua in https://github.com/insightsengineering/teal.modules.clinical/issues/263#issuecomment-995341463_

**Comment by shajoezhu** [comment]
1. compare odds_ratio <- function(x, conf_level = 0.95)  vs clogit with an example, see where the differences (please track in this thread)
2. replace the usage of clogit by function "odds_ratio <- function(x, conf_level = 0.95)"
3. test with real data

**Comment by 6iris6** [comment]
From TLGC RSPT01 Best Overall Response (with stratified analysis), the odds ratio and CI are as follow:
![Screen Shot 2022-11-15 at 5 02 10 PM](https://user-images.githubusercontent.com/98936068/202057740-049dd765-07eb-4dde-b753-976cf67f273b.png)
Odds Ratio (95% CI)    0.57 (0.34 - 0.96)   0.54 (0.32 - 0.91)

So I'm using the above odds_ratio function to check the differences. And I am using the same data as in RSPT01
```
library(dplyr)
library(tern)
library(scda)
adsl <- synthetic_cdisc_dataset("latest", "adsl")
adrs <- synthetic_cdisc_dataset("latest", "adrs")
adsl <- df_explicit_na(adsl)
adrs <- df_explicit_na(adrs)

anl_adrs <- adrs %>%
  filter(PARAMCD == "INVET") %>%
  select(STUDYID, USUBJID, PARAMCD, AVISIT, AVALC)
anl_adsl <- adsl %>%
  select(STUDYID, USUBJID, ARM, STRATA1)

anl <- anl_adsl %>%
  left_join(anl_adrs, by = c("STUDYID", "USUBJID")) %>%
  mutate(rsp_lab = d_onco_rsp_label(AVALC)) %>%
  mutate(is_rsp = AVALC %in% c("CR", "PR")) %>%
  mutate(ARM = relevel(ARM, ref = "A: Drug X")) %>%
  var_relabel(ARM = "Description of Planned Arm")

odds_ratio <- function(x, conf_level = 0.95) {
  
  theta <- x[1, 1] * x[2, 2] / (x[2, 1] * x[1, 2])
  # Asymptotic standard error
  ase <- sqrt(sum(1 / x))
  ci <- exp(log(theta) + c(-1, 1) * qnorm(0.5 * (1 + conf_level)) * ase)
  
  list(
    estimator = theta,
    se = ase,
    conf.int = ci,
    conf_level = conf_level
  )
}

#odds ratio function only works on 2*2
#For Placebo arm
anl_ab<-anl%>%filter(ARM %in% c("A: Drug X", "B: Placebo"))
#table(anl_ab$is_rsp,anl_ab$ARM)
anl_ab_mx <- matrix(c(84,100,50,34), nrow = 2, byrow = TRUE)
odds_ratio(anl_ab_mx, conf_level = 0.95)
#0.5712 (0.3384336 0.9640574)
#same as RSPT01 table

# For ARM C
anl_ac<-anl%>%filter(ARM %in% c("A: Drug X", "C: Combination"))
#table(anl_ac$is_rsp,anl_ac$ARM)
anl_ac_mx <- matrix(c(81,100,51,34), nrow = 2, byrow = TRUE)
odds_ratio(anl_ac_mx, conf_level = 0.95)
#0.54(0.3198905 0.9115619)
#same as RSPT01 table
```
So the results are the same. I will follow up with Joel if he still has this issue.

**Comment by 6iris6** [comment]
After talking to Joel and running all the codes again, I think the root cause is not because the above ```odds_ratio <- function(x, conf_level = 0.95)```.

The difference is from the adjusted odds ratio and CI.  Clogit is used In both tern and Joel's code, however the result can't match with SAS result, and this is my test result as well (using Joel's study data). From an old ticket https://github.roche.com/NEST/tern/issues/851, Joel also commented 'though the OR and ORCI using clogit() doesn't seem to be matching up with our STREAM output.'  And below is my code 
```
#Joel's study data
pat<- 'root/clinical_studies/RO5541267/CDT30091/YO40245/data_analysis/ADA_OS_31AUG2020/prod/outdata_vad'
all<- rice::rice_read_all(pat)
ADSL<- all$adsla
ADRS<- all$adrsa

ADRS$AVALC[ADRS$AVALC==""] <- "Miss"


ADSL_FILTERED <- dplyr::filter(
  ADSL,
  ANLMN6O %in% c("ADA-", "ADA+", "Sorafenib 400 mg BID"),
  BMEASIFL == "Y",
  SAFFL == "Y",
  ADJBLFL == "Y"
)
{
  ADRS_FILTERED_ALONE <- dplyr::filter(
    ADRS,
    AVALC %in% c(
      "CR", "Miss", "NE", "NON-CR/NON-PD",
      "PD", "PR", "SD"
    )
  )
  ADRS_FILTERED <- dplyr::inner_join(
    x = ADSL_FILTERED[, c("STUDYID", "USUBJID")],
    y = ADRS_FILTERED_ALONE,
    by = c("STUDYID", "USUBJID")
  )
}



anl_endpoint <- subset(ADRS_FILTERED, PARAMCD == "CBORDF")
adsl_p <- subset(ADSL_FILTERED, ANLMN6O %in% c("Sorafenib 400 mg BID", c("ADA-", "ADA+")))
anl <- merge(
  x = adsl_p[, c("USUBJID", "STUDYID", "ANLMN6O", "REGION1", "AFPC", "MVI_EHS"), drop = FALSE],
  y = anl_endpoint[, c("USUBJID", "STUDYID", "AVAL", "AVALC", "PARAMCD"), drop = FALSE],
  all.x = FALSE,
  all.y = FALSE,
  by = c("USUBJID", "STUDYID")
)%>%
  mutate(is_rsp = AVALC %in% c("CR", "PR"))%>%
  mutate(rsp_lab = d_onco_rsp_label(AVALC))

# arm <- relevel(as.factor(anl[["ANLMN6O"]]), "Sorafenib 400 mg BID"[1])
# arm <- combine_levels(arm, "Sorafenib 400 mg BID")
# anl[["ANLMN6O"]] <- droplevels(arm)

#NEST RSPT01
strata <-c("REGION1", "AFPC", "MVI_EHS")
lyt_04 <- basic_table() %>%
  split_cols_by(var = "ANLMN6O", ref_group = "Sorafenib 400 mg BID") %>%
  add_colcounts() %>%
  estimate_proportion(
    vars = "is_rsp",
    table_names = "est_prop",
    method = "clopper-pearson"
  ) %>%
  estimate_proportion_diff(
    vars = "is_rsp",
    show_labels = "visible",
    var_labels = "Stratified Analysis",
    method = "waldcc",
    variables = list(strata = strata),
    table_names = "est_prop_diff_strat"
  ) %>%
  test_proportion_diff(
    vars = "is_rsp",
    method = "cmh",
    variables = list(strata = strata),
    table_names = "test_prop_strat"
  ) %>%
  estimate_odds_ratio(
    vars = "is_rsp",
    variables = list(strata = strata, arm = "ANLMN6O"),
    table_names = "est_or_strat"
  ) %>%
  estimate_multinomial_response(var = "rsp_lab",method = "clopper-pearson")
result <- build_table(lyt = lyt_04, df = anl)
result

```
Everything matches except the odds ratio and CI.
                                          Sorafenib 400 mg BID          ADA-                 ADA+       
                                                 (N=141)               (N=235)               (N=59)      
—————————————————————————————————————————————————————————————————————————————————————————————————————————
Responders                                      18 (12.8%)            76 (32.3%)           17 (28.8%)    
95% CI (Clopper-Pearson)                       (7.7, 19.4)           (26.4, 38.7)         (17.8, 42.1)   
Stratified Analysis                                                                                      
  Difference in Response rate (%)                                        19.6                 16.0       
    95% CI (Wald, with correction)                                   (10.9, 28.3)         (2.0, 30.1)    
  p-value (Cochran-Mantel-Haenszel Test)                               <0.0001               0.0012      
Odds Ratio (95% CI)                                               3.45 (1.93 - 6.16)   3.35 (1.54 - 7.29)
Complete Response (CR)                           1 (0.7%)             19 (8.1%)             5 (8.5%)     
  95% CI (Clopper-Pearson)                     (0.02, 3.89)         (4.94, 12.34)        (2.81, 18.68)   
Miss                                             6 (4.3%)              0 (0.0%)             1 (1.7%)     
  95% CI (Clopper-Pearson)                     (1.58, 9.03)          (0.00, 1.56)         (0.04, 9.09)   
Not Evaluable (NE)                              11 (7.8%)              5 (2.1%)             0 (0.0%)     
  95% CI (Clopper-Pearson)                    (3.96, 13.53)          (0.69, 4.90)         (0.00, 6.06)   
Partial Response (PR)                           17 (12.1%)            57 (24.3%)           12 (20.3%)    
  95% CI (Clopper-Pearson)                    (7.18, 18.60)         (18.92, 30.25)       (10.98, 32.83)  
Progressive Disease (PD)                        38 (27.0%)            41 (17.4%)           16 (27.1%)    
  95% CI (Clopper-Pearson)                    (19.83, 35.07)        (12.82, 22.92)       (16.36, 40.27)  
Stable Disease (SD)                             68 (48.2%)           113 (48.1%)           25 (42.4%)    
  95% CI (Clopper-Pearson)                    (39.74, 56.79)        (41.54, 54.67)       (29.61, 55.93)

**Comment by 6iris6** [comment]
I'm able to match my SAS result with R result by using following code:
```proc logistic data=import descending;
  class grp(ref='Sorafenib 400 mg BID') strata;
  model rsp = grp ;
  strata strata;
run;
```


![Image](https://user-images.githubusercontent.com/98936068/204460972-07b4ad2b-3149-4366-b079-a99e742fef77.png)

However, it's still different from STREAM output. Need to understand what option STREAM used...

**Comment by 6iris6** [comment]
Finally match the R output & my SAS output vs STREAM output! In a summary, STREAM fits different treatment groups into different logistic models, instead of fitting all levels into the same model. Here's my R code for modifying the anl dataset:
```
anl1 <- anl %>% filter (ANLMN6O !='ADA+')
anl2 <- anl %>% filter (ANLMN6O !='ADA-')

result1 <- build_table(lyt = lyt_04, df = anl1)
result2 <- build_table(lyt = lyt_04, df = anl2)
```

And here's the result
```
                                           Sorafenib 400 mg BID          ADA-       
                                                 (N=141)               (N=235)      
————————————————————————————————————————————————————————————————————————————————————
Responders                                      18 (12.8%)            76 (32.3%)    
95% CI (Clopper-Pearson)                       (7.7, 19.4)           (26.4, 38.7)   
Stratified Analysis                                                                 
  Difference in Response rate (%)                                        19.6       
    95% CI (Wald, with correction)                                   (10.9, 28.3)   
  p-value (Cochran-Mantel-Haenszel Test)                               <0.0001      
Odds Ratio (95% CI)                                               3.41 (1.92 - 6.05)
Complete Response (CR)                           1 (0.7%)             19 (8.1%)     
  95% CI (Clopper-Pearson)                     (0.02, 3.89)         (4.94, 12.34)   
Miss                                             6 (4.3%)              0 (0.0%)     
  95% CI (Clopper-Pearson)                     (1.58, 9.03)          (0.00, 1.56)   
Not Evaluable (NE)                              11 (7.8%)              5 (2.1%)     
  95% CI (Clopper-Pearson)                    (3.96, 13.53)          (0.69, 4.90)   
Partial Response (PR)                           17 (12.1%)            57 (24.3%)    
  95% CI (Clopper-Pearson)                    (7.18, 18.60)         (18.92, 30.25)  
Progressive Disease (PD)                        38 (27.0%)            41 (17.4%)    
  95% CI (Clopper-Pearson)                    (19.83, 35.07)        (12.82, 22.92)  
Stable Disease (SD)                             68 (48.2%)           113 (48.1%)    
  95% CI (Clopper-Pearson)                    (39.74, 56.79)        (41.54, 54.67)  
```

```
                                           Sorafenib 400 mg BID          ADA+       
                                                 (N=141)                (N=59)      
————————————————————————————————————————————————————————————————————————————————————
Responders                                      18 (12.8%)            17 (28.8%)    
95% CI (Clopper-Pearson)                       (7.7, 19.4)           (17.8, 42.1)   
Stratified Analysis                                                                 
  Difference in Response rate (%)                                        16.0       
    95% CI (Wald, with correction)                                   (2.0, 30.1)    
  p-value (Cochran-Mantel-Haenszel Test)                                0.0012      
Odds Ratio (95% CI)                                               3.85 (1.64 - 9.02)
Complete Response (CR)                           1 (0.7%)              5 (8.5%)     
  95% CI (Clopper-Pearson)                     (0.02, 3.89)         (2.81, 18.68)   
Miss                                             6 (4.3%)              1 (1.7%)     
  95% CI (Clopper-Pearson)                     (1.58, 9.03)          (0.04, 9.09)   
Not Evaluable (NE)                              11 (7.8%)              0 (0.0%)     
  95% CI (Clopper-Pearson)                    (3.96, 13.53)          (0.00, 6.06)   
Partial Response (PR)                           17 (12.1%)            12 (20.3%)    
  95% CI (Clopper-Pearson)                    (7.18, 18.60)         (10.98, 32.83)  
Progressive Disease (PD)                        38 (27.0%)            16 (27.1%)    
  95% CI (Clopper-Pearson)                    (19.83, 35.07)        (16.36, 40.27)  
Stable Disease (SD)                             68 (48.2%)            25 (42.4%)    
  95% CI (Clopper-Pearson)                    (39.74, 56.79)        (29.61, 55.93)  
```

Same for SAS code, I subset only one treatment group and placebo at one time.

**Comment by 6iris6** [comment]
@shajoezhu Could you please check my last comment? I think this ticket could be closed now.

**Comment by shajoezhu** [comment]
Thank you so much @6iris6 ! This is really informative. Yes, we can close this issue now. We can follow up with this in tmc with a separate issue.
