### ISSUE TITLE
Issue with strata in g__lineplot()

### ISSUE THREAD

**Issue by qiliu1013** [insightsengineering/tern#664]
`g_lineplot()` is re-setting the factor level in `strata`.

```
adsl <- scda::synthetic_cdisc_data("latest")$adsl
adlb <- scda::synthetic_cdisc_data("latest")$adlb
adlb <- dplyr::filter(adlb, ANL01FL == "Y", PARAMCD == "ALT", AVISIT != "SCREENING")
adlb$AVISIT <- droplevels(adlb$AVISIT)
adlb <- dplyr::mutate(adlb, AVISIT = forcats::fct_reorder(AVISIT, AVISITN, min))
unique(adlb$ARM)
[1] A: Drug X      C: Combination B: Placebo    
Levels: A: Drug X B: Placebo C: Combination

adlb <- adlb %>% mutate(ARM1 = factor(ARM, levels = c("B: Placebo", "C: Combination", "A: Drug X")))
unique(adlb$ARM1)
[1] A: Drug X      C: Combination B: Placebo    
Levels: B: Placebo C: Combination A: Drug X

 tern::g_lineplot(
     adlb, strata = ARM,
     whiskers = "mean_ci_upr",
     title = "Plot of Mean and Upper 95% Confidence Limit by Visit"
 )

tern::g_lineplot(
     adlb, strata = ARM1,
     whiskers = "mean_ci_upr",
     title = "Plot of Mean and Upper 95% Confidence Limit by Visit"
 )
```
The level of ARM and ARM1 are different, but the outputs are the same.

![Screen Shot 2022-08-04 at 11 29 24 AM](https://user-images.githubusercontent.com/24441440/182925276-713a6738-d82d-4dbc-b3e2-59e3bcc400d7.png)

**Comment by qiliu1013** [comment]
Hi @shajoezhu, I tested it using the code from help doc. Same issue occurs.

Thanks,
Qi

**Comment by edelarua** [comment]
Hi @qiliu1013,

`g_lineplot` uses a control function `control_lineplot_vars` to customize arguments such as `strata` for `g_lineplot`. Since `strata` is not directly an argument for `g_lineplot`, differing the variables for `strata` in your code above do not change the plot. To create these plots, the correct code is:

```r
tern::g_lineplot(
  adlb, 
  variables = control_lineplot_vars(strata = "ARM"),
  whiskers = "mean_ci_upr",
  title = "Plot of Mean and Upper 95% Confidence Limit by Visit"
)
```
![Image](https://user-images.githubusercontent.com/59304861/183976217-6d52c91c-527b-43d7-ac38-7d932ea92ae7.png)

```r
tern::g_lineplot(
  adlb, 
  variables = control_lineplot_vars(strata = "ARM1"),
  whiskers = "mean_ci_upr",
  title = "Plot of Mean and Upper 95% Confidence Limit by Visit"
)
```
![Image](https://user-images.githubusercontent.com/59304861/183976234-a62a1cc9-3fd0-4b15-bcda-57361b8e5308.png)
