### ISSUE TITLE
insightsengineering.github.io article tab not showing all list

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#761]
There are two articles, and only one is shown under https://insightsengineering.github.io/tern/articles/tern.html "article" tab

full list can be seen at

https://insightsengineering.github.io/tern/articles/index.html

**Comment by edelarua** [comment]
@shajoezhu this is expected behavior. When a vignette file is named `repo_name.Rmd` (in this case `tern.Rmd`), instead of listing this vignette under the "Articles" tab it is accessible via the "Get started" tab. If the filename is changed then it will be listed under "Articles" but the "Get started" tab will disappear.

**Comment by shajoezhu** [comment]
This sounds very odd to me. we can investigate a little when have some spare time, low priority for now

**Comment by Melkiades** [comment]
I think it is still fine like this, it is an intro, and "get started" will surely be clicked by people that want to go through an intro first. It is also standard so it is still intuitive imo. On the other hand, it is important to me to add more vignettes explaining "modules" of things that can be done in tern. I will open a new issue about that and I think we should close this.
