### ISSUE TITLE
0 count value summary leads to NA of mean and sd, Inf in min and max

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/tern#796]
I still need to review the precision implementation, but wanted to quickly raise default behaviour issue. If no values are collected (n=0) then in STREAM we see the below,
![image](https://user-images.githubusercontent.com/87320028/211817484-0d7c4b99-78aa-4847-a255-f702d2e22bf3.png)
but currently in chevron we get warnings and the below,
![image](https://user-images.githubusercontent.com/87320028/211817608-0a4224dc-d0bc-4403-8280-830d9882ca8f.png)
![image](https://user-images.githubusercontent.com/87320028/211817705-21cbff02-4817-44f7-80f3-b76ce63f759f.png)

_Originally posted by @barnett11 in https://github.com/insightsengineering/chevron/pull/343#pullrequestreview-1243905311_

**Comment by shajoezhu** [comment]
Let's create customized format for handling this. @clarkliming I was wondering what the expected output (values) should look like?

**Comment by edelarua** [comment]
@shajoezhu there is an argument `.format_na_strs` in `rtables::make_afun()` that allows the user to specify a string to replace NA values (see function [here](https://github.com/Roche/rtables/blob/main/R/tt_afun_utils.R#L140)). I can look into implementing this argument in all of the `tern` analysis functions (similar to the `.formats` argument) so that this can be customized in any table.

**Comment by shajoezhu** [comment]
;p=[Thanks a lot @edelarua , that is exactlly what we will use. first we need to know how these values will be displayed. @barnett11 @clarkliming

**Comment by barnett11** [comment]
> 

This is how it is displayed currently in STREAM @shajoezhu ,
![image](https://user-images.githubusercontent.com/87320028/212919651-ccdf374f-facd-489f-81b1-0ade28d0a90a.png)

**Comment by shajoezhu** [comment]
ah! Gotcha! Thanks Tim! @barnett11
