### ISSUE TITLE
`count_occurrences_by_grade` missing occurrences?

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#798]
>  Hey @Melkiades I was just looking at the last example with the result dataset being generated on line 430. The rtable outputs a value of 5 for `Grade 1-2`, when looking at the `df` should it not be 6 patients?
> ![image](https://user-images.githubusercontent.com/56098440/212180364-8158952d-2dc6-4606-86cf-7eeebb0046e1.png)
> ![image](https://user-images.githubusercontent.com/56098440/212180459-78d08275-3f86-4eef-85bf-bc963f0539ad.png)

_Originally posted by @Nolan-Steed in https://github.com/insightsengineering/tern/issues/794#issuecomment-1380990047_

**Comment by edelarua** [comment]
@Melkiades @Nolan-Steed in this case this is the expected output of the table. 

The `s_count_occurrences_by_grade` function is described as "Statistics function which given occurrence data counts the number of patients _by highest grade_". You can see that there are two records with `USUBJID = 1`, so this function includes row 7 (with `AETOXGR = 3`) instead of row 1 (with `AETOXGR = 1`) as the record for this patient. This is also why although there are 8 records in `df`, only 7 are counted in the `-Any-` total (7 total unique patients).
