### ISSUE TITLE
Issues from integration tests

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/tern#802]
```
Warning (test-abnormal_by_marked.R:33:3): s_count_abnormal_by_marked works as expected
  `vec_unchop()` was deprecated in vctrs 0.5.0.
  Please use `list_unchop()` instead.
   
   Error (test-g_forest.R:21:3): g_forest default plot works
  Error: 'expect_no_error' is not an exported object from 'namespace:testthat'
  
    Warning (test-g_km.R:8:3): g_km default plot works
  The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
  Please use the `linewidth` argument instead.
  
  
    Failure (test-g_lineplot.R:12:3): g_lineplot works with custom settings and statistics table
  `g_lineplot(...)` produced warnings.
```

- [ ] `abnormal_by_marked` warning
- [x] `g_forest` error https://github.com/insightsengineering/tern/pull/803
- [x] `g_km` warning https://github.com/insightsengineering/nestcolor/pull/42
- [x] `g_lineplot` error https://github.com/insightsengineering/nestcolor/pull/42

**Comment by edelarua** [comment]
@Melkiades I looked into the error log:

- `abnormal_by_baseline` warning:

```
  Warning (test-abnormal_by_marked.R:207:3): count_abnormal_by_marked works as expected
  `vec_unchop()` was deprecated in vctrs 0.5.0.
  Please use `list_unchop()` instead.
  Backtrace:
   1. input_data %>% dplyr::group_by(USUBJID, PARAMCD) %>% ...
        at test-abnormal_by_worst_grade_worsen.R:20:2
   3. dplyr:::mutate.data.frame(...)
   4. dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
   6. vctrs::vec_unchop(chunks, rows)
```
It seems like `dplyr` hasn't updated their usage of several deprecated `vctrs` functions that are used in the `dplyr:::mutate_cols` or `dplyr:::join_rows` functions, so we won't be able to fix those warnings. It gives this warning for ~20 tests in `tern`.

---

- `g_lineplot`/`g_km` errors:

I think the `g_*` function tests should all be fixed by https://github.com/insightsengineering/nestcolor/pull/42.

**Comment by Melkiades** [comment]
I think we need to keep the first warnings eheh

What do you think regarding this @arkadiuszbeer?
