### ISSUE TITLE
rewrite and simplify example in "summarize_ancova" with iris dataset

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern#807]
This will enable us to avoid the use of adqs data in the example

to get started, consider the following

```R
df <- iris %>%
  filter(Species == "virginica")
.df_row <- iris 
.var <- "Petal.Length"

variables <- list(arm = "Species", covariates = "Sepal.Length * Sepal.Width")
.ref_group <- iris %>%
  filter(Species == "setosa")
conf_level <- 0.95

tern:::s_ancova(
  df, .var, .df_row, variables, .ref_group,
  .in_ref_col = FALSE,
  conf_level, interaction_y = FALSE, interaction_item = NULL
)

tern:::a_ancova(
  df, .var, .df_row, variables, .ref_group,
  .in_ref_col = FALSE,
  interaction_y = FALSE, interaction_item = NULL, conf_level
)

```

**Comment by Melkiades** [comment]
@edelarua is working on creating reduced data. We could grasp the opportunity to create data that is a bit more meaningful across different unit tests. I thought about this and I would replace each data, one at a time, following the setup file, instead of going from function to function. In this way, we can divide the problem into smaller (agile) chunks while also keeping an eye on the final (intended) implementation for TLGs. This would, in turn, be useful to control the completeness of unit tests. What do you think @edelarua @shajoezhu?

**Comment by shajoezhu** [comment]
Hi @Melkiades , the vision for future tern is to compute the statistics, if possible, I would love to drop all clinical data, and make it more general. the improtant part for tern is the functions to derive the statisitcs. 

however, there are functions that definitely are dedicated for clinical statistics usage, perhaps, at some stage, we will split tern again. for now, we won't have to keep all data from scda, just need a few ones, see https://github.com/insightsengineering/tern/issues/778#issue-1501733998

these data are linked with the fake patient id, i would like to simplify this by just taking the current data, and reduce its size. if we can reduce adsl from 400 patient to 300 paitent, it reduces things quite a lot already, and drop the columns that we are unlikely to use again.
