### ISSUE TITLE
Add test

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tern#995]
Autovalidate report:
```
Consistency checks failed:
 - requirement #0.073 'Formatting Count and Fraction' is not covered by any test
```

**Comment by shajoezhu** [comment]
Hi @pawelru and @Melkiades , I flagged this as a false positive perviously. also see 
https://github.com/insightsengineering/tern/pull/987#pullrequestreview-1498834839

hey @dgkf-roche , I was wondering if we could get some help regarding this? Thanks so much!

**Comment by dgkf-roche** [comment]
Sorry for missing the @ tag. I'll take a look at my notification settings because I don't think I'm getting emails when tagged here.

But I can confirm, we've seen this issue in the past and it hasn't been an issue. Our tools for aligning documentation and code objects will sometimes miss tested behaviors. We err on the side of being sensitive to possibly untested behaviors, so we'll occasionally have these falsely identified "untested" behaviors.

We're constantly trying to improve the way we associate code with documentation in [`covtracer`](https://github.com/Genentech/covtracer), but there are many edge cases, especially with S4/R6 objects. For any code that is generated at build-time (in `tern`, that would include functions generated using `make_afun()`), it is nearly impossible to exactly associate documentation. That's not to say you shouldn't do it! It looks like a very useful construct for reusing code. It just means our conservative tooling might not always realize what code is tied to what docs.

I filed [an issue in `covtracer`](https://github.com/Genentech/covtracer/issues/72) to investigate more closely, but an important take-away here is that our tools are intentionally conservative and might occasionally flag behaviors that are actually tested. We see these results as being primarily in support of our review of packages, not as a checklist.

**Comment by shajoezhu** [comment]
Thanks Doug for confirming!
